### ISSUE TITLE
Make Inline PAR compatible

### ISSUE THREAD

**Issue by zdm** [ingydotnet/inline-pm#54]
Hi.

Is it possible to make 'lib' suffix in Inline.pm line 927 configurable?
```
$o->{API}{install_lib} = Spec->catdir($o->{INLINE}{DIRECTORY}, 'lib');
```
PAR can properly load shared objects from following locations inside archive:
```
/lib/                           # standard location
/arch/                        # for creating from blib/ 
/i386-freebsd/           # i.e. $Config{archname}
/5.8.0/                       # i.e. Perl version number
/5.8.0/i386-freebsd/  # combination of the two above
/                                # casual packaging only
```
And hardcoded 'lib' prevent to place Inline data to right arch - dependent location.

If 'lib' will be configurable, I can configure inline dir as '/5.8.0/i386-freebsd/', so 'auto/' dir will be findable by standard perl tools, which looking for 'auto' in @INC.

**Comment by mohawk2** [comment]
Take a look at Inline::Module, also by Ingy.

**Comment by zdm** [comment]
This is not preferable approach. 
I have a project, that use Inline and just want to pack it to PAR directly, without creating and installing intermediate CPAN distribution.

**Comment by mohawk2** [comment]
Inline::Module places the generated shared object (aka DLL) into blib/arch. If PAR can't then use that, I will be most surprised.

**Comment by zdm** [comment]
Inline::Module is not helpful.
I can manually put generated xs objects everywhere in PAR during build, but problem is that I should write additional loader, that recognize, that project was started from PAR and load xs manually.
So, instead of using standard Inline code everywhere, like:
```
Inline->import(
    config => (
        directory         => $P->{INLINE_DIR},
        autoname          => 0,
        clean_after_build => 1,
        clean_build_area  => 1,
    )
);
```
I need to create additional wrappers, like:
```
if ( $PAR )  {
    # load xs manually, using DynaLoader
}
else {
    # use standard Inline code
}
```
This will be much more easier for support and maintenance to use standard, well - documented Inline approach everywhere.

**Comment by zdm** [comment]
I don't need Inline::Module, because I don't need to build my projects separately before packing to PAR.
I already has xs, built in _Inline dir, and want to pack them together with project working copy.

**Comment by zdm** [comment]
Problem solved.
